name: movie
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  dio: ^3.0.9
  auto_route: ^0.5.0
  shimmer: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.5.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
